# Generated by Django 2.1.2 on 2018-11-20 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('permissions', models.CharField(max_length=4)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('officehours', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=50)),
                ('lectureSectionCount', models.IntegerField()),
                ('labSectionCount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courselist', to='taapp.Account')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courselist', to='taapp.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('sectionID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sectionName', models.CharField(max_length=50)),
                ('sectionCount', models.IntegerField()),
                ('sectionType', models.IntegerField()),
                ('parentCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taapp.Course')),
            ],
        ),
        migrations.CreateModel(
            name='SectionMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sectionlist', to='taapp.Account')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sectionlist', to='taapp.Section')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='courses',
            field=models.ManyToManyField(related_name='courses', through='taapp.CourseMember', to='taapp.Course'),
        ),
        migrations.AddField(
            model_name='account',
            name='sections',
            field=models.ManyToManyField(related_name='sections', through='taapp.SectionMember', to='taapp.Section'),
        ),
    ]
