# Generated by Django 2.1.2 on 2018-11-20 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='sectionCount',
        ),
    ]
